CONFIG_EXFAT_FS=y
CONFIG_SQUASHFS=y
CONFIG_SQUASHFS_LZ4=y
CONFIG_SQUASHFS_LZO=y
CONFIG_SQUASHFS_XZ=y
CONFIG_OVERLAY_FS=y
CONFIG_ARM64_4K_PAGES=y
### for SPI LCD hat built-in (remove these if you use HDMI instead of SPI LCD hat)
CONFIG_SPI_BCM2835=y
CONFIG_DRM=y
CONFIG_DRM_KMS_HELPER=y
CONFIG_DRM_GEM_DMA_HELPER=y
CONFIG_DRM_MIPI_DBI=y
CONFIG_DRM_PANEL_MIPI_DBI=y
CONFIG_FB_BCM2708=m
CONFIG_BACKLIGHT_PWM=y
CONFIG_PWM_BCM2835=y
CONFIG_PWM_GPIO=y
CONFIG_EXTRA_FIRMWARE="panel-mipi-dbi-spi.bin"
CONFIG_EXTRA_FIRMWARE_DIR="$(BR2_EXTERNAL_TiniLinux_PATH)/board/pi3b/linux/external-firmware/panels"
### end for SPI LCD hat built-in