#ifndef __KEYBOARD_H__
#define __KEYBOARD_H__

#include <SDL2/SDL.h>

#define KMOD_SYNTHETIC (1 << 14)

#define JOYBUTTON_UP 13
#define JOYBUTTON_DOWN 14
#define JOYBUTTON_LEFT 15
#define JOYBUTTON_RIGHT 16
#define JOYBUTTON_A 1
#define JOYBUTTON_B 0
#define JOYBUTTON_X 2
#define JOYBUTTON_Y 3
#define JOYBUTTON_SELECT 8
#define JOYBUTTON_START 9
#define JOYBUTTON_L1 4
#define JOYBUTTON_R1 5
#define JOYBUTTON_L2 6
#define JOYBUTTON_R2 7
#define JOYBUTTON_L3 11
#define JOYBUTTON_R3 12
#define JOYBUTTON_MENU 10

#ifdef BR2 // Buildroot handhelds with SDL2

#define KEY_UP JOYBUTTON_UP
#define KEY_DOWN JOYBUTTON_DOWN
#define KEY_LEFT JOYBUTTON_LEFT
#define KEY_RIGHT JOYBUTTON_RIGHT
#define KEY_ENTER JOYBUTTON_A
#define KEY_TOGGLE JOYBUTTON_R1
#define KEY_BACKSPACE JOYBUTTON_B
#define KEY_SHIFT JOYBUTTON_L1
#define KEY_LOCATION JOYBUTTON_Y
#define KEY_ACTIVATE JOYBUTTON_X
#define KEY_QUIT JOYBUTTON_MENU
#define KEY_TAB JOYBUTTON_SELECT
#define KEY_RETURN JOYBUTTON_START
#define KEY_ARROW_LEFT JOYBUTTON_L2
#define KEY_ARROW_RIGHT JOYBUTTON_R2
#define KEY_ARROW_UP JOYBUTTON_L3
#define KEY_ARROW_DOWN JOYBUTTON_R3

#else
// generic Linux PC
#define KEY_UP SDLK_UP
#define KEY_DOWN SDLK_DOWN
#define KEY_LEFT SDLK_LEFT
#define KEY_RIGHT SDLK_RIGHT
#define KEY_ENTER SDLK_F10
#define KEY_TOGGLE SDLK_LALT
#define KEY_BACKSPACE SDLK_BACKSPACE
#define KEY_SHIFT SDLK_LSHIFT
#define KEY_LOCATION SDLK_F11
#define KEY_ACTIVATE SDLK_F12
#define KEY_QUIT SDLK_HOME
#define KEY_TAB SDLK_TAB
#define KEY_RETURN SDLK_RETURN
#define KEY_ARROW_LEFT SDLK_PAGEUP
#define KEY_ARROW_RIGHT SDLK_PAGEDOWN
#define KEY_ARROW_UP SDLK_KP_DIVIDE
#define KEY_ARROW_DOWN SDLK_KP_PERIOD

#endif

void init_keyboard();
void draw_keyboard(SDL_Surface *surface);
int handle_keyboard_event(SDL_Event *event);
int handle_narrow_keys_held(int sym);
extern int active;
extern int show_help;

#endif
