## Disable Init Utilities as we use systemd
CONFIG_HALT=n
CONFIG_POWEROFF=n
CONFIG_REBOOT=n
CONFIG_INIT=n
CONFIG_LINUXRC=n

## Add dpkg
#CONFIG_DPKG=y # you may need to enable zstd package support as well
