#!/bin/sh

#####
#
# /init for BusyBox initramfs -> real root
#
#####
echo "[initramfs] Booting..."

# Mount pseudo filesystems
mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t devtmpfs dev /dev
mount -t tmpfs tmpfs /run

# Parse kernel command line
for param in $(cat /proc/cmdline); do
    case $param in
        root=*)
            root="${param#root=}"
            ;;
        init=*)
            init="${param#init=}"
            ;;
        overlayfs=*)
            overlayfs="${param#overlayfs=}"
            ;;
        squashfspart=*)
            squashfspart="${param#squashfspart=}"
            ;;
        squashfsroot=*)
            squashfsroot="${param#squashfsroot=}"
            ;;
    esac
done

mkdir -p /newroot
INIT_UNIT=""

# if overlayfs is specified, set up OverlayFS
if [ -n "$overlayfs" ] && [ -n "$squashfspart" ] && [ -n "$squashfsroot" ]; then
    echo "[initramfs] Setting up OverlayFS: lower from $squashfspart/$squashfsroot, upper on $overlayfs"
    mkdir -p /mnt/boot /mnt/overlay_lower /mnt/rw
    mount -o ro "$squashfspart" /mnt/boot || exec sh
    mount -t squashfs -o loop,ro "/mnt/boot/$squashfsroot" /mnt/overlay_lower || exec sh
    mount -o rw "$overlayfs" /mnt/rw || exec sh

    # Check for rootfs resize flags
    if [ -f /mnt/rw/overlay_upper/root/.resize-rootfs ]; then
        mv /mnt/rw/overlay_upper/root/.resize-rootfs /mnt/rw/overlay_upper/root/.resize-rootfs-done # fs-resize.sh won't know the flag, so we remove it here
        INIT_UNIT="--unit=fs-resize@rootfs.service"
        umount $overlayfs || exec sh
        mount --move /mnt/overlay_lower /newroot || exec sh
    else
        mkdir -p /mnt/rw/overlay_upper /mnt/rw/overlay_workdir
        mount -t overlay overlay -o lowerdir=/mnt/overlay_lower,upperdir=/mnt/rw/overlay_upper,workdir=/mnt/rw/overlay_workdir /newroot || exec sh
        if [ -f /newroot/root/.resize-romsfs ]; then
            # /root/.resize-romsfs flag will be removed by fs-resize.sh after resizing
            INIT_UNIT="--unit=fs-resize@romsfs.service"
        fi
    fi
    mount --move /mnt/boot /newroot/boot || exec sh
else # no OverlayFS, just mount root directly
    echo "[initramfs] No OverlayFS specified, using root=$root directly."
    mount -o rw "$root" /newroot || exec sh

    # Check for rootfs resize flags
    if [ -f /newroot/root/.resize-rootfs ]; then
        mv /newroot/root/.resize-rootfs /newroot/root/.resize-rootfs-done
        INIT_UNIT="--unit=fs-resize@rootfs.service"
    elif [ -f /newroot/root/.resize-romsfs ]; then
        # /root/.resize-romsfs flag will be removed by fs-resize.sh after resizing
        INIT_UNIT="--unit=fs-resize@romsfs.service"
    fi
fi

# Mount runtime dirs for systemd
mount --move /proc /newroot/proc
mount --move /sys /newroot/sys
mount --move /dev /newroot/dev
mount --move /run /newroot/run

echo "[initramfs] Switching to real root..."
exec switch_root /newroot ${init:-/sbin/init} $INIT_UNIT || exec sh
