# The Raspberry Pi 3B+ does not support a traditional "suspend to RAM" or hibernation mode like a desktop PC. It is designed to be powered 24/7, and issuing a standard suspend command will generally not put it into a low-power state. This will help fake suspend with screen blanking
[Service]
ExecStart=
ExecStart=/bin/sh -c "echo 1 > /sys/class/graphics/fb1/blank || true"
ExecStart=/bin/sh -c "echo 1 > /sys/class/graphics/fb0/blank || true"