#!/bin/busybox sh

#####
#
# TiniLinux initramfs init script
#
#####

echo "TiniLinux Booting..."
. /lib/init-functions.sh

# Mount pseudo filesystems
mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t devtmpfs dev /dev
mount -t tmpfs tmpfs /run

# Parse kernel command line
for param in $(cat /proc/cmdline); do
    case $param in
        root=*)
            root="${param#root=}"
            ;;
        init=*)
            init="${param#init=}"
            ;;
        overlayfs=*)
            overlayfs="${param#overlayfs=}"
            ;;
        bootpart=*)
            bootpart="${param#bootpart=}"
            ;;
        fsck.repair=*)
            case "${param#fsck.repair=}" in
                yes)   fsck_opt="-y" ;;
                no)    fsck_opt="-n" ;;
                preen) fsck_opt="-a" ;;
                *)     fsck_opt="-a" ;;
            esac
            ;;
        setfont=*)
            setfont="${param#setfont=}"
            ;;
        networkconf=*)
            networkconf="${param#networkconf=}"
            ;;
        debug)
            debug=yes
            ;;
        quiet)
            quiet=yes
            ;;
    esac
done


# Set console font if specified
if [ -n "$setfont" ]; then
    log "[initramfs] Setting console font to $setfont..."
    setfont -C /dev/console "/usr/share/consolefonts/$setfont" || log "[initramfs] Warning: Failed to set console font to $setfont"
fi

# Create new root directory
mkdir -p /newroot
INIT_UNIT=""

if [ -n "$overlayfs" ] && [ -n "$bootpart" ]; then
    # overlayfs is specified, set up squashfs mounts
    mount_squashfs
else
    # mount root from NFS or from local disk
    # root=nfs:server:/path
    # root=/dev/mmcblk0p2
    case "$root" in
        nfs:*)
            nfs_target="${root#nfs:}"
            nfs_server="${nfs_target%%:*}"
            nfs_path="${nfs_target#*:}"
            ;;
    esac

    if [ -n "$nfs_server" ]; then
        mount_nfs
    else
        mount_local_root
    fi
fi

# if debug=yes, drop to shell before switching root
if [ "$debug" = "yes" ]; then
    if [ -n "$bootpart" ] && [ -z "$overlayfs" ]; then
        mkdir -p /mnt/boot
        log "[initramfs] Mounting boot partition $bootpart for debugging..."
        mount -o rw "$bootpart" /mnt/boot
    fi
    echo "[initramfs] Debug mode enabled - dropping to shell before switching root. Run ". /lib/init-functions.sh" then "do_switch_root" to continue booting after debugging"
    sh
fi

do_switch_root
