name: Build (separated jobs) (dry run)
on:
  workflow_dispatch:
    inputs:
      board:
        description: 'Select board to build'
        required: true
        type: choice
        options:
          - h700
          - h700_consoleonly
          - h700_sway
          - rgb30
          - rgb30_consoleonly
          - raspberrypi3_64
      runner:
        description: 'Select runner type'
        required: true
        type: choice
        options:
          - github-hosted_ubuntu-24.04
          - self-hosted_debian12-sachchat2
          - self-hosted_ubuntu-24.04
          - self-hosted_ubuntu-25.04-arm

run-name: (Dry run) Build for ${{ inputs.board }} on ${{ inputs.runner }}

jobs:
  build:
    runs-on: ${{ (inputs.runner == 'github-hosted_ubuntu-24.04' && 'ubuntu-24.04') || (inputs.runner == 'self-hosted_debian12-sachchat2' && fromJSON('["self-hosted","debian12-sachchat2"]')) || (inputs.runner == 'self-hosted_ubuntu-24.04' && fromJSON('["self-hosted","ubuntu-24.04"]')) || (inputs.runner == 'self-hosted_ubuntu-25.04-arm' && fromJSON('["self-hosted","ubuntu-25.04-arm"]')) }}
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          path: TiniLinux
      - name: Checkout buildroot repo
        uses: actions/checkout@v4
        with:
          repository: buildroot/buildroot
          ref: 2025.08.1
          path: buildroot
      - name: Build
        run: |
          set -x
          ls -la . && cd buildroot
          make O=../TiniLinux/output.${{ inputs.board }} BR2_EXTERNAL=../TiniLinux ${{ inputs.board }}_defconfig
          cd ../TiniLinux/output.${{ inputs.board }}

          # Simulate build output files
          mkdir -p images/allwinner
          mkdir -p images/rockchip
          mkdir -p images/rk3566-dtbo/
          touch images/Image
          touch images/initramfs
          touch images/allwinner/h700.dtb
          touch images/u-boot-rockchip.bin
          touch images/rockchip/rk3566.dtb
          touch images/rk3566-dtbo/rk3566.dtbo
          touch images/u-boot-sunxi-with-spl.bin
          mkdir -p target/root
          mkdir -p target/etc
          touch target/root/init.sh
          echo "BUILD_ID=buildroot" > target/etc/os-release
          tar -cvf images/rootfs.tar -C target/ .
          touch images/sdcard.img

          cd ..
      - name: Upload result for next job
        uses: actions/upload-artifact@v4
        with:
          name: images_dir
          path: |
            output.${{ inputs.board }}/images/
          retention-days: 2

  mkflashableimg:
    needs: build
    runs-on: ${{ (inputs.runner == 'github-hosted_ubuntu-24.04' && 'ubuntu-24.04') || (inputs.runner == 'self-hosted_debian12-sachchat2' && fromJSON('["self-hosted","debian12-sachchat2"]')) || (inputs.runner == 'self-hosted_ubuntu-24.04' && fromJSON('["self-hosted","ubuntu-24.04"]')) || (inputs.runner == 'self-hosted_ubuntu-25.04-arm' && fromJSON('["self-hosted","ubuntu-25.04-arm"]')) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download images_dir result from build job
        uses: actions/download-artifact@v5
        with:
          name: images_dir
          path: output.${{ inputs.board }}/images/
      - name: Make flashable image
        run: |
          set -x
          if [ "${{ inputs.board }}" = "raspberrypi3_64" ]; then
            mv output.${{ inputs.board }}/images/sdcard.img output.${{ inputs.board }}/images/tinilinux-${{ inputs.board }}.img
          elif sudo -n true &> /dev/null; then
            echo "Current user has passwordless sudo privileges. Calling faster mk-flashable-img script"
            sudo BOARD=${{ inputs.board }} board/common/mk-flashable-img.sh
          else
            echo "Current user does not have passwordless sudo privileges (or requires a password). Calling rootless (slower) mk-flashable-img script"
            BOARD=${{ inputs.board }} board/common/mk-flashable-img-rootless.sh
          fi
      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: tinilinux-${{ inputs.board }}.img
          path: output.${{ inputs.board }}/images/tinilinux-${{ inputs.board }}.img
          retention-days: 2