name: Daily refresh cache (pi3b)

on:
  schedule:
    - cron: '0 11 */4 * *' # every 4th day-of-month at 11AM UTC
  workflow_dispatch: {}

jobs:
  refresh-cache:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v5
        with:
          path: TiniLinux

      - name: Create board build config
        run: |
          set -x
          cd TiniLinux
          ./scripts/make-board-build.sh configs/pi3b_defconfig
          cd output/pi3b

      - name: Restore dl cache
        uses: actions/cache@v5
        with:
          path: TiniLinux/dl
          key: dl-cache-pi3b-${{ hashFiles('TiniLinux/output/pi3b/.config') }}
          restore-keys: |
            dl-cache-pi3b-

      - name: Restore ccache
        uses: actions/cache@v5
        with:
          path: TiniLinux/.buildroot-ccache
          key: ccache-pi3b-${{ hashFiles('TiniLinux/output/pi3b/.config') }}
          restore-keys: |
            ccache-pi3b-
